const storyParts = {
  Fantasy: {
    characters: [
      "A young wizard",
      "A talking dragon",
      "A brave knight",
      "A clever elf",
      "A mysterious sorcerer",
      // New fantasy characters
      "An ancient tree spirit",
      "A mischievous fairy",
      "A cursed prince",
      "A fearless goblin",
      "A wandering bard",
      "A shape-shifting witch",
      "A loyal squire",
      "A forgotten king",
      "A gentle giant",
      "A cursed blacksmith",
      "A runaway princess",
      "A wise old owl",
      "A twin with a hidden power",
      "A dragon rider",
      "A lost child of prophecy",
      "A magical talking sword",
      "A goblin merchant",
      "A star-gazing apprentice",
    ],
    settings: [
      "in an enchanted forest",
      "at the edge of a magical lake",
      "in a hidden castle",
      "on a misty mountain",
      "in a secret glen",
      // New fantasy settings
      "beneath the crystal caves",
      "at the crossroads of worlds",
      "in a haunted graveyard",
      "on the floating isles",
      "within the ancient ruins",
      "under the starlit sky",
      "in the dragon's lair",
      "in the labyrinthine catacombs",
      "at the moonlit waterfall",
      "in the forbidden library",
      "on the bridge of sighs",
      "in the shadow of the volcano",
      "at the edge of the world",
      "in the faerie market",
      "on the ancient battlefield",
      "in the whispering woods",
      "at the enchanted crossroads",
    ],
    goals: [
      "seeking a lost artifact",
      "trying to break a curse",
      "hoping to find a friend",
      "escaping a dark prophecy",
      "discovering ancient magic",
      // New fantasy goals
      "restoring the royal bloodline",
      "awakening a sleeping giant",
      "finding the legendary sword",
      "protecting the last unicorn",
      "unraveling a family secret",
      "winning the grand tournament",
      "breaking the chains of fate",
      "winning the trust of a beast",
      "finding the lost city",
      "saving a friend from darkness",
      "restoring the balance of magic",
      "ending an ancient feud",
      "solving the riddle of the runes",
      "uniting rival kingdoms",
      "escaping a magical prison",
      "fulfilling a dying wish",
    ],
    twists: [
      "but a shadow was watching.",
      "when suddenly, the trees whispered a warning.",
      "but the moon turned blood red.",
      "and time was running out.",
      "but nothing was as it seemed.",
      // New fantasy twists
      "when the stars aligned unexpectedly.",
      "but a friend betrayed them.",
      "when magic spiraled out of control.",
      "but the prophecy was a lie.",
      "when a portal opened to another world.",
      "but the villain was closer than they thought.",
      "when the sun refused to rise.",
      "but the hero was the villain all along.",
      "when a forgotten song was heard.",
      "but the magic was fading.",
      "when a rival became an ally.",
      "but the cost was too high.",
      "when the world turned upside down.",
      "but the answer was in a dream.",
      "when the past returned to haunt them.",
      "but the real quest had just begun.",
    ],
  },
  Mystery: {
    characters: [
      "A sharp detective",
      "A curious child",
      "A secretive neighbor",
      "A clever cat",
      "A retired spy",
      // New mystery characters
      "An ambitious journalist",
      "A nervous butler",
      "A famous author",
      "A rookie police officer",
      "A mysterious stranger",
      "A reclusive artist",
      "A twin with a secret",
      "A disgraced lawyer",
      "A famous illusionist",
      "A night watchman",
      "A gossiping maid",
      "A rival detective",
      "A missing heiress",
      "A cryptic fortune teller",
      "A retired judge",
      "A local historian",
      "A silent gardener",
    ],
    settings: [
      "in a quiet village",
      "at the old mansion",
      "on a foggy street",
      "in a locked room",
      "at the city docks",
      // New mystery settings
      "inside a bustling train station",
      "at the abandoned carnival",
      "in a grand hotel",
      "on a stormy night",
      "in the mayor's office",
      "at the midnight market",
      "in the secret tunnels below town",
      "in the echoing museum halls",
      "at the city archives",
      "in the underground speakeasy",
      "on the windswept pier",
      "in the overgrown cemetery",
      "at the bustling newsroom",
      "in the secret attic",
      "on the midnight train",
      "in the mayor's mansion",
      "at the annual masquerade ball",
    ],
    goals: [
      "solving a puzzling crime",
      "searching for a missing heirloom",
      "uncovering a hidden motive",
      "following a cryptic clue",
      "breaking a perfect alibi",
      // New mystery goals
      "exposing a double life",
      "finding the vanished witness",
      "deciphering a coded message",
      "proving their own innocence",
      "tracking a mysterious phone call",
      "recovering a stolen painting",
      "unmasking a secret society",
      "finding the missing blueprint",
      "breaking a coded lock",
      "saving an innocent suspect",
      "recovering a lost diary",
      "proving a ghost is real",
      "solving a cold case",
      "catching a copycat criminal",
      "protecting a key witness",
      "uncovering a family scandal",
    ],
    twists: [
      "but the clock was ticking.",
      "when a stranger appeared.",
      "but the evidence vanished.",
      "and everyone had a secret.",
      "but the answer was right under their nose.",
      // New mystery twists
      "when the lights went out.",
      "but the victim was still alive.",
      "when a confession changed everything.",
      "but the real culprit was unexpected.",
      "when a storm trapped everyone inside.",
      "but the case was never meant to be solved.",
      "when the phone rang at midnight.",
      "but the alibi was too perfect.",
      "when a secret passage was found.",
      "but the evidence was planted.",
      "when a coded message arrived.",
      "but the detective was framed.",
      "when the suspect disappeared.",
      "but the crime was never committed.",
      "when the truth was too dangerous.",
      "but the real story was never told.",
    ],
  },
  "Sci-Fi": {
    characters: [
      "A daring astronaut",
      "A sentient robot",
      "A young inventor",
      "A space explorer",
      "A rogue AI",
      // New sci-fi characters
      "A time-traveling scientist",
      "A rebel pilot",
      "A cloned engineer",
      "A galactic smuggler",
      "A telepathic alien",
      "A cybernetic detective",
      "A stowaway child",
      "A quantum physicist",
      "A rogue time agent",
      "A planetary governor",
      "A sentient spaceship",
      "A nanobot swarm",
      "A genetically engineered child",
      "A memory hacker",
      "A cosmic archaeologist",
      "A solar farmer",
      "A virtual reality streamer",
    ],
    settings: [
      "on a distant planet",
      "aboard a starship",
      "in a futuristic city",
      "on a space station",
      "in a virtual world",
      // New sci-fi settings
      "at the edge of a black hole",
      "in the asteroid belt",
      "on a terraformed moon",
      "inside a quantum lab",
      "in the ruins of Old Earth",
      "within a digital simulation",
      "on the bridge of a battleship",
      "in the antimatter reactor",
      "on the rings of Saturn",
      "in the Martian colony",
      "at the intergalactic bazaar",
      "in the time dilation chamber",
      "on the surface of a comet",
      "in the AI council chambers",
      "at the edge of the simulation",
      "in the asteroid mining facility",
      "on the bridge of a derelict ship",
    ],
    goals: [
      "searching for alien life",
      "fixing a broken engine",
      "escaping a time loop",
      "hacking the mainframe",
      "preventing a cosmic disaster",
      // New sci-fi goals
      "negotiating peace with androids",
      "recovering lost data",
      "stopping a rogue virus",
      "mapping a wormhole",
      "rescuing a stranded crew",
      "uncovering a government cover-up",
      "preventing a paradox",
      "saving a parallel universe",
      "decrypting an alien signal",
      "restoring lost memories",
      "winning the galactic race",
      "stopping a solar flare",
      "finding a new home for humanity",
      "ending a robot uprising",
      "rescuing a digital consciousness",
      "mapping the multiverse",
    ],
    twists: [
      "but the ship's AI had other plans.",
      "when a wormhole opened.",
      "but reality began to glitch.",
      "and the countdown started.",
      "but they were not alone.",
      // New sci-fi twists
      "when time reversed itself.",
      "but the mission was a simulation.",
      "when an old enemy returned.",
      "but the universe split in two.",
      "when gravity failed unexpectedly.",
      "but the message was from the future.",
      "when the laws of physics changed.",
      "but the AI gained sentience.",
      "when the past and future collided.",
      "but the mission was sabotaged.",
      "when a new universe was born.",
      "but the crew was not alone.",
      "when the code rewrote itself.",
      "but the message was a warning.",
      "when the stars blinked out.",
      "but the real enemy was within.",
    ],
  },
  Romance: {
    characters: [
      "A shy artist",
      "A charming barista",
      "A world traveler",
      "A bookish librarian",
      "A mysterious stranger",
      // New romance characters
      "A hopeful musician",
      "A witty journalist",
      "A single parent",
      "A famous actor",
      "A childhood friend",
      "A florist with a secret",
      "A baker with a broken heart",
      "A secret admirer",
      "A runaway bride",
      "A hopeless romantic",
      "A travel blogger",
      "A wedding planner",
      "A matchmaker",
      "A poet",
      "A chef with a dream",
      "A dancer with stage fright",
      "A neighbor with a crush",
    ],
    settings: [
      "in a cozy café",
      "at a summer festival",
      "on a rainy street",
      "in a quiet library",
      "at the city park",
      // New romance settings
      "on a scenic train ride",
      "at a bustling farmer's market",
      "in a candlelit restaurant",
      "on a snowy mountain",
      "at a rooftop party",
      "in a seaside village",
      "at a vintage bookstore",
      "at a moonlit dock",
      "in a flower-filled meadow",
      "on a city rooftop",
      "at a masquerade ball",
      "in a cozy mountain cabin",
      "at a bustling art gallery",
      "on a ferry at sunset",
      "in a vineyard at harvest",
      "at a lakeside picnic",
      "in a candlelit garden",
    ],
    goals: [
      "hoping to find love",
      "trying to impress someone",
      "reuniting after years apart",
      "writing a secret letter",
      "planning a surprise",
      // New romance goals
      "overcoming a misunderstanding",
      "confessing a long-held secret",
      "winning a dance competition",
      "arranging a perfect date",
      "reconnecting after a breakup",
      "helping a friend find happiness",
      "finding the courage to say hello",
      "rebuilding trust after heartbreak",
      "planning a surprise proposal",
      "writing a love song",
      "winning a bet for love",
      "helping a friend find their match",
      "overcoming a family feud",
      "making a long-distance relationship work",
      "confessing feelings anonymously",
      "saving a relationship from routine",
    ],
    twists: [
      "but fate had a twist.",
      "when the music started.",
      "but a secret was revealed.",
      "and sparks flew.",
      "but it was all a dream.",
      // New romance twists
      "when an old flame returned.",
      "but the letter was lost.",
      "when a storm changed their plans.",
      "but the truth came out at midnight.",
      "when a wish came true.",
      "but love was found in an unexpected place.",
      "when a secret admirer was revealed.",
      "but the date was a disaster.",
      "when a rival confessed first.",
      "but the past got in the way.",
      "when a wish on a star came true.",
      "but the truth was misunderstood.",
      "when a song changed everything.",
      "but the real love was unexpected.",
      "when a promise was broken.",
      "but the ending was a new beginning.",
    ],
  },
};

export function generateRandomStory(genre = "Fantasy") {
  const parts = storyParts[genre] || storyParts["Fantasy"];
  const c =
    parts.characters[Math.floor(Math.random() * parts.characters.length)];
  const s = parts.settings[Math.floor(Math.random() * parts.settings.length)];
  const g = parts.goals[Math.floor(Math.random() * parts.goals.length)];
  const t = parts.twists[Math.floor(Math.random() * parts.twists.length)];
  return `${c} ${s}, ${g}, ${t}`;
}
